# Products Routes
POST http://localhost:3000/products/create
Content-Type: application/json

{
    "sku": 101,
    "name": "Teste de pet 2",
    "price": 100,
    "gender": "male",
    "size": "medium",
    "age": "2 months",
    "color": ["Black"],
    "vaccinated": true,
    "dewormed": false,
    "certified": "MKA",
    "microchip": true,
    "location": "Brazil",
    "addInfo": ["Pure breed Shih Tzu.", "Good body structure.", "With MKA cert and Microchip.", "Father from champion lineage."],
    "images": ["https://www.daxia.com.br/ptbr/wp-content/uploads/2021/05/iStock-1271494334-750x325.jpg"],
    "type": "PET"
}

### 

GET http://localhost:3000/products?limit=2&offset=0&size=large

### 

GET http://localhost:3000/products/1

###

PATCH http://localhost:3000/products/1
Content-Type: application/json

{
    "images": ["https://www.daxia.com.br/ptbr/wp-content/uploads/2021/05/iStock-1271494334-750x325.jpg"]
}

###

DELETE http://localhost:3000/products/1